# Generated by Django 5.2.13 on 2026-05-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_alter_language_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('provider', models.CharField(default='replicate_f5tts', max_length=50, verbose_name='Провайдер')),
                ('voice_preset', models.CharField(default='default', max_length=50, verbose_name='Голос')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидание'), ('processing', '🔄 В процессе'), ('completed', '✅ Готово'), ('failed', '❌ Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_projects/', verbose_name='Аудиофайл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудио проект',
                'verbose_name_plural': 'Аудио проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст для озвучки')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_tracks/', verbose_name='Аудиофайл')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидание'), ('processing', '🔄 Генерация'), ('success', '✅ Готово'), ('failed', '❌ Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='audio.audioproject')),
            ],
            options={
                'verbose_name': 'Аудиотрек',
                'verbose_name_plural': 'Аудиотреки',
                'ordering': ['order'],
            },
        ),
    ]
