# Generated by Django 5.2.13 on 2026-05-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_language_options'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioproject',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to='article.articlecluster'),
        ),
    ]
