# Generated by Django 5.2.13 on 2026-04-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Идея', 'verbose_name_plural': 'Идеи'},
        ),
    ]
