# Generated by Django 5.2.13 on 2026-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_videoproject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='idea_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код промпта'),
        ),
    ]
