# Generated by Django 5.2.13 on 2026-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_videoproject_idea_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('provider', models.CharField(default='openai', max_length=50, verbose_name='AI провайдер')),
                ('research_data', models.JSONField(blank=True, default=dict, help_text='Сырой JSON от AI: facts, scores, hooks, visual_moments...', verbose_name='Исследовательские данные (JSON)')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('ready', 'Данные готовы'), ('script_generated', 'Сценарий создан'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Исследование (JSON)',
                'verbose_name_plural': 'Исследования (JSON)',
                'ordering': ['-created_at'],
            },
        ),
    ]
