# Generated by Django 5.2.13 on 2026-06-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_researchproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
