# Generated by Django 5.2.13 on 2026-06-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_language_options'),
        ('topics', '0005_alter_researchproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Глобальная тема или ниша исследования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_projects', to='article.articlecluster'),
        ),
    ]
