# Generated by Django 5.2.13 on 2026-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_researchproject_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='selected_images',
            field=models.JSONField(blank=True, default=list, help_text='Изображения, выбранные AI для этой темы', verbose_name='Выбранные изображения'),
        ),
    ]
