# Generated by Django 5.2.13 on 2026-04-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема видео')),
                ('angle', models.TextField(help_text='Основная идея или технологический парадокс', verbose_name='Ракурс / Парадокс')),
                ('notes', models.TextField(help_text='Детальные факты, даты, имена, вопросы для исследования', verbose_name='Заметки / Факты')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Готовое видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Изображение'), ('audio', 'Аудио'), ('script', 'Текст сценария')], max_length=10, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/%Y/%m/%d/', verbose_name='Файл')),
                ('content_text', models.TextField(blank=True, verbose_name='Текстовое содержание')),
                ('prompt_used', models.TextField(blank=True, verbose_name='Промпт')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='generator.videoproject')),
            ],
        ),
    ]
