# Generated by Django 5.2.13 on 2026-04-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_mediaasset_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
        migrations.AlterModelOptions(
            name='videoproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Видеопроект', 'verbose_name_plural': 'Видеопроекты'},
        ),
        migrations.CreateModel(
            name='ScriptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_full', models.TextField(blank=True, default='', verbose_name='Полный сценарий (EN)')),
                ('script_ru', models.TextField(blank=True, default='', verbose_name='Перевод RU')),
                ('script_de', models.TextField(blank=True, default='', verbose_name='Перевод DE')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок видео')),
                ('hashtags', models.TextField(blank=True, default='', verbose_name='Хэштеги')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script_data', to='generator.videoproject')),
            ],
            options={
                'verbose_name': 'Данные сценария',
                'verbose_name_plural': 'Данные сценариев',
            },
        ),
    ]
