# Generated by Django 5.2.13 on 2026-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_mediaasset_options_alter_videoproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptdata',
            name='scene_breakdown',
            field=models.JSONField(blank=True, default=list, verbose_name='Разбивка на сцены'),
        ),
    ]
