# Generated by Django 5.2.13 on 2026-04-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_scriptdata_scene_breakdown'),
        ('image', '0002_alter_imageprompt_project'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='topics.videoproject'),
        ),
        migrations.AlterField(
            model_name='scriptdata',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script_data', to='topics.videoproject'),
        ),
        migrations.DeleteModel(
            name='VideoProject',
        ),
    ]
