# Generated by Django 5.2.13 on 2026-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание для превью (SEO)', verbose_name='Описание (Description)'),
        ),
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.CharField(blank=True, help_text='5 хештегов через пробел, например: #история #тайны', max_length=255, verbose_name='Хештеги'),
        ),
    ]
