# Generated by Django 5.2.13 on 2026-04-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options_article_description_and_more'),
        ('topics', '0002_alter_videoproject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='en, ru, de...', max_length=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('flag_emoji', models.CharField(blank=True, max_length=5, verbose_name='Флаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': '1. Языки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SceneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип сцены',
                'verbose_name_plural': '2. Типы сцен',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи (Одиночные)'},
        ),
        migrations.CreateModel(
            name='ArticleCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('source_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_clusters', to='topics.videoproject')),
            ],
            options={
                'verbose_name': 'Статья (Кластер)',
                'verbose_name_plural': 'Управление статьями (Кластеры)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='article.language'),
        ),
        migrations.CreateModel(
            name='ImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Промпт (EN)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL картинки')),
                ('is_generated', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='article.article')),
                ('scene_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='article.scenetype')),
            ],
            options={
                'verbose_name': 'Промпт изображения',
                'verbose_name_plural': '3. Промпты изображений',
                'ordering': ['scene_type__order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание (SEO)')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('hashtags', models.CharField(blank=True, max_length=255, verbose_name='Хештеги')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='article.articlecluster')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_translations', to='article.language')),
            ],
            options={
                'verbose_name': 'Перевод статьи',
                'verbose_name_plural': 'Переводы статей',
                'ordering': ['language__order'],
                'unique_together': {('cluster', 'language')},
            },
        ),
    ]
