# Generated by Django 5.2.13 on 2026-05-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_language_scenetype_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
    ]
