# Generated by Django 5.2.13 on 2026-06-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_language_options'),
        ('topics', '0007_researchproject_selected_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Версия')),
                ('script_data', models.JSONField(blank=True, default=dict, verbose_name='Текст скрипта (JSON)')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Количество слов')),
                ('estimated_duration', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность (сек)')),
                ('provider', models.CharField(default='openai', max_length=50, verbose_name='AI провайдер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cluster', models.ForeignKey(blank=True, help_text='Кластер (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_scripts', to='article.articlecluster')),
                ('research_project', models.ForeignKey(help_text='Исследование, на основе которого создан текст', on_delete=django.db.models.deletion.CASCADE, related_name='video_scripts', to='topics.researchproject')),
            ],
            options={
                'verbose_name': 'Текст для ролика',
                'verbose_name_plural': 'Тексты для роликов',
                'ordering': ['-created_at'],
            },
        ),
    ]
