# Generated by Django 5.2.13 on 2026-04-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0003_alter_mediaasset_options_alter_videoproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Текст промпта')),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Vertical (9:16) - TikTok/Reels'), ('16:9', 'Horizontal (16:9) - YouTube'), ('1:1', 'Square (1:1) - Post'), ('4:3', 'Classic (4:3)')], default='9:16', max_length=10, verbose_name='Размер')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Картинка создана')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/', verbose_name='Готовая картинка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='generator.videoproject')),
            ],
            options={
                'verbose_name': 'Промпт для картинки',
                'verbose_name_plural': 'Промпты для картинок',
                'ordering': ['order'],
            },
        ),
    ]
