# Generated by Django 5.2.13 on 2026-04-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprompt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='topics.videoproject'),
        ),
    ]
