# Generated by Django 5.2.13 on 2026-05-03 13:51

import django.db.models.deletion
import image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_language_scenetype_alter_article_options_and_more'),
        ('image', '0002_alter_imageprompt_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageprompt',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='imageprompt',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='imageprompt',
            name='generated_image',
        ),
        migrations.RemoveField(
            model_name='imageprompt',
            name='is_generated',
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('generating', 'В процессе'), ('success', 'Успех'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус генерации'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=image.models.upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='scene_description',
            field=models.TextField(blank=True, help_text='Что происходит в кадре', verbose_name='Описание сцены (для человека)'),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сцены'),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='prompt_text',
            field=models.TextField(help_text='На английском языке', verbose_name='Текст промпта (для AI)'),
        ),
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название проекта')),
                ('style_preset', models.CharField(choices=[('cinematic', 'Cinematic Dark (Кино)'), ('realistic', 'Photorealistic (Фото)'), ('anime', 'Anime Style'), ('oil_painting', 'Oil Painting'), ('cyberpunk', 'Cyberpunk'), ('custom', 'Свой стиль...')], default='cinematic', max_length=50, verbose_name='Стиль')),
                ('custom_style_prompt', models.TextField(blank=True, help_text="Например: '8k, highly detailed, dramatic lighting'", verbose_name='Доп. описание стиля')),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 (YouTube)'), ('9:16', '9:16 (TikTok)'), ('1:1', '1:1 (Post)')], default='16:9', max_length=10, verbose_name='Формат')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('prompts_ready', 'Промпты готовы'), ('processing', 'Генерация изображений...'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_projects', to='article.articlecluster')),
            ],
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='image.imageproject'),
        ),
    ]
