# Generated by Django 5.2.13 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_imageprompt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprompt',
            name='images_generated',
            field=models.BooleanField(default=False, verbose_name='Картинки созданы'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='prompts_generated',
            field=models.BooleanField(default=False, verbose_name='Промпты созданы'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Поисковый заголовок'),
        ),
    ]
