# Generated by Django 5.2.13 on 2026-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_remove_imageprompt_images_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='aspect_ratio',
            field=models.CharField(choices=[('16:9', '16:9 (YouTube)'), ('9:16', '9:16 (TikTok)'), ('1:1', '1:1 (Post)')], default='9:16', max_length=10, verbose_name='Формат'),
        ),
    ]
