# Generated by Django 5.2.13 on 2026-06-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_imageproject_aspect_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproject',
            options={'verbose_name': 'Проект картинки', 'verbose_name_plural': 'Проекты картинок'},
        ),
        migrations.AlterModelOptions(
            name='imageprompt',
            options={'ordering': ['order'], 'verbose_name': 'Проект промпт', 'verbose_name_plural': 'Проекты промптов'},
        ),
    ]
