# Generated by Django 5.2.13 on 2026-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: openai, gemini, hf', max_length=50, unique=True, verbose_name='Кодовое имя')),
                ('display_name', models.CharField(help_text='Например: OpenAI GPT-4o', max_length=100, verbose_name='Отображаемое имя')),
                ('provider_type', models.CharField(choices=[('llm', 'Текст / LLM'), ('image', 'Изображения'), ('audio', 'Аудио / Голос'), ('video', 'Видео')], max_length=20, verbose_name='Тип')),
                ('api_key', models.TextField(blank=True, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, help_text='Если отличается от стандартного', null=True, verbose_name='Base URL')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON с параметрами модели', verbose_name='Конфигурация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Провайдер',
                'verbose_name_plural': 'AI Провайдеры',
                'ordering': ['provider_type', 'name'],
            },
        ),
    ]
