# Generated by Django 5.2.13 on 2026-04-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=models.TextField(blank=True, editable=False, verbose_name='API Key (Зашифрован)'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='base_url',
            field=models.URLField(blank=True, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Отображаемое имя'),
        ),
    ]
