# Generated by Django 5.2.13 on 2026-04-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_inspector', '0002_alter_aiprovider_api_key_alter_aiprovider_base_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['provider_type', 'name'], 'verbose_name': 'Провайдер ИИ', 'verbose_name_plural': 'Провайдеры ИИ'},
        ),
    ]
