# Generated by Django 5.2.13 on 2026-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_inspector', '0003_alter_aiprovider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=models.TextField(blank=True, verbose_name='API Key (Зашифрован)'),
        ),
    ]
