# Generated by Django 5.2.13 on 2026-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_mode', models.CharField(choices=[('manual', '🛠 Ручной (Пошаговый контроль)'), ('auto', '🤖 Полный Автопилот (One-Click)')], default='manual', max_length=10, verbose_name='Режим работы')),
                ('openai_key', models.CharField(blank=True, help_text='sk-...', max_length=255, verbose_name='OpenAI API Key')),
                ('gemini_key', models.CharField(blank=True, max_length=255, verbose_name='Google Gemini API Key')),
                ('hf_key', models.CharField(blank=True, help_text='hf_...', max_length=255, verbose_name='HuggingFace API Key')),
                ('elevenlabs_key', models.CharField(blank=True, max_length=255, verbose_name='ElevenLabs API Key (Voice)')),
                ('default_article_model', models.CharField(choices=[('gpt-4o', 'GPT-4o (Best Quality)'), ('gpt-4o-mini', 'GPT-4o Mini (Fast/Cheap)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Smart)')], default='gpt-4o', max_length=50, verbose_name='Модель для статей')),
                ('default_image_model', models.CharField(choices=[('flux-schnell', 'Flux Schnell (Fast)'), ('flux-dev', 'Flux Dev (High Quality)'), ('sdxl', 'Stable Diffusion XL')], default='flux-schnell', max_length=50, verbose_name='Модель для картинок')),
                ('auto_translate_languages', models.CharField(default='ru,de', help_text='Через запятую, например: ru,de,es', max_length=50, verbose_name='Языки для авто-перевода')),
                ('auto_generate_images', models.BooleanField(default=True, verbose_name='Авто: Генерировать картинки после статьи')),
                ('auto_generate_voice', models.BooleanField(default=False, verbose_name='Авто: Генерировать озвучку')),
                ('auto_assemble_video', models.BooleanField(default=False, verbose_name='Авто: Монтировать видео в конце')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
