# Generated by Django 5.2.13 on 2026-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Классический хук', 'Конспирология'", max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('structure_prompt', models.TextField(help_text='Инструкция для AI. Используй переменные {topic}, {angle}, {notes}.', verbose_name='Промпт структуры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон структуры статьи',
                'verbose_name_plural': 'Шаблоны структур статей',
            },
        ),
    ]
