# Generated by Django 5.2.13 on 2026-04-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Historical Facts Finder'", max_length=100, verbose_name='Название шаблона')),
                ('code_name', models.SlugField(help_text="Используется в коде. Например: 'idea_facts_v1'", unique=True, verbose_name='Кодовое имя')),
                ('prompt_type', models.CharField(choices=[('idea_generation', 'Генерация идей (Факты/Вопросы)'), ('article_writing', 'Написание статьи'), ('image_prompt', 'Генерация промпта для картинки'), ('scriptwriting', 'Написание сценария')], max_length=50, verbose_name='Тип')),
                ('template_content', models.TextField(help_text='Используй {topic}, {count}, {language} как переменные.', verbose_name='Текст промпта (EN)')),
                ('is_active', models.BooleanField(default=True, help_text='Только активный шаблон используется в генерации', verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, help_text='Если активных несколько, используется этот', verbose_name='По умолчанию')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
