# Generated by Django 5.2.13 on 2026-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code_name', models.SlugField(help_text="Уникальный ID для кода, например 'idea_facts_v1'", unique=True, verbose_name='Кодовое имя')),
                ('description', models.TextField(blank=True, help_text='Для чего этот промпт? (на русском)', verbose_name='Описание')),
                ('template_content', models.TextField(help_text='Шаблон на английском. Переменные: {topic}, {context}, {language} и т.д.', verbose_name='Текст промпта (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промпт для Статьи',
                'verbose_name_plural': '3. Промпты для Статей',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code_name', models.SlugField(help_text="Уникальный ID для кода, например 'idea_facts_v1'", unique=True, verbose_name='Кодовое имя')),
                ('description', models.TextField(blank=True, help_text='Для чего этот промпт? (на русском)', verbose_name='Описание')),
                ('template_content', models.TextField(help_text='Шаблон на английском. Переменные: {topic}, {context}, {language} и т.д.', verbose_name='Текст промпта (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.CharField(choices=[('facts', 'Факты и Вопросы'), ('sensational', 'Сенсационный/Кликбейт'), ('mystery', 'Загадки и Тайны'), ('educational', 'Образовательный/Строгий')], default='facts', max_length=50, verbose_name='Стиль подачи')),
            ],
            options={
                'verbose_name': 'Промпт для Идеи',
                'verbose_name_plural': '1. Промпты для Идей',
                'ordering': ['-is_active', 'style'],
            },
        ),
        migrations.CreateModel(
            name='StructurePlanPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code_name', models.SlugField(help_text="Уникальный ID для кода, например 'idea_facts_v1'", unique=True, verbose_name='Кодовое имя')),
                ('description', models.TextField(blank=True, help_text='Для чего этот промпт? (на русском)', verbose_name='Описание')),
                ('template_content', models.TextField(help_text='Шаблон на английском. Переменные: {topic}, {context}, {language} и т.д.', verbose_name='Текст промпта (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промпт для Плана Статьи',
                'verbose_name_plural': '2. Промпты для Планов (Структура)',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
