# Generated by Django 5.2.13 on 2026-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_articleprompt_ideaprompt_structureplanprompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprompt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='pending'),
        ),
        migrations.AlterField(
            model_name='ideaprompt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='pending'),
        ),
        migrations.AlterField(
            model_name='structureplanprompt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='pending'),
        ),
    ]
