# Generated by Django 5.2.13 on 2026-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_alter_articleprompt_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StructurePlanPrompt',
            new_name='SystemInstruction',
        ),
        migrations.AlterModelOptions(
            name='systeminstruction',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Системная Инструкция', 'verbose_name_plural': '2. Системные Инструкции'},
        ),
    ]
