# Generated by Django 5.2.13 on 2026-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_rename_structureplanprompt_systeminstruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code_name', models.SlugField(help_text="Уникальный ID для кода, например 'idea_facts_v1'", unique=True, verbose_name='Кодовое имя')),
                ('description', models.TextField(blank=True, help_text='Для чего этот промпт? (на русском)', verbose_name='Описание')),
                ('template_content', models.TextField(help_text='Шаблон на английском. Переменные: {topic}, {context}, {language} и т.д.', verbose_name='Текст промпта (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='pending')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_format', models.CharField(choices=[('json_list', 'JSON List ( [{"desc": "...", "prompt": "..."}] )'), ('json_object', 'JSON Object ( {"scenes": [...]} )'), ('markdown', 'Markdown Table')], default='json_list', help_text='Подсказка для модели, в каком формате вернуть данные.', max_length=20, verbose_name='Предпочитаемый формат ответа')),
            ],
            options={
                'verbose_name': 'Шаблон для Изображений (Раскадровка)',
                'verbose_name_plural': '4. Промпты для Изображений',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
