# Generated by Django 5.2.13 on 2026-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_imageprompttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Например: universal, shock, doc', unique=True, verbose_name='Код промпта')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('prompt_text', models.TextField(verbose_name='Текст промпта')),
                ('config', models.JSONField(blank=True, default=dict, help_text='{"min_scenes": 4, "max_scenes": 7, "lang": "en"}', verbose_name='Настройки генерации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промпт для сценария',
                'verbose_name_plural': 'Промпты для сценариев',
                'ordering': ['-updated_at'],
            },
        ),
    ]
