# Generated by Django 5.2.13 on 2026-06-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_scriptprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptprompt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Промпт для сценария', 'verbose_name_plural': '5. Промпты для сценариев'},
        ),
    ]
