# Generated by Django 5.2.13 on 2026-06-02 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideoRelease',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID проекта')),
                ('pj_title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('pj_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания проекта')),
                ('video_created_at', models.DateTimeField(auto_now=True, verbose_name='Дата сборки видео')),
                ('pj_datatime_clip', models.DateTimeField(verbose_name='Дата удаления файла')),
                ('pj_link', models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='Файл видео')),
                ('pj_status', models.CharField(choices=[('rendering', 'В процессе сборки'), ('ready', 'Готово к скачиванию'), ('expired', 'Файл видео удален (история сохранена)'), ('failed', 'Ошибка генерации')], default='rendering', max_length=20, verbose_name='Статус')),
                ('pj_config', models.JSONField(default=list, verbose_name='История конфигураций сценария')),
            ],
            options={
                'db_table': 'project_video_releases',
            },
        ),
    ]
