# Generated by Django 5.2.13 on 2026-06-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoeditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectvideorelease',
            options={'verbose_name': 'Готовый видеопроект', 'verbose_name_plural': 'Готовые видеопроекты'},
        ),
        migrations.AlterModelTable(
            name='projectvideorelease',
            table=None,
        ),
    ]
