# Generated by Django 5.2.13 on 2026-06-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audioproject_article'),
        ('videoeditor', '0002_alter_projectvideorelease_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideorelease',
            name='project_id',
        ),
        migrations.AddField(
            model_name='projectvideorelease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='projectvideorelease',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_releases', to='audio.audioproject'),
            preserve_default=False,
        ),
    ]
