# Generated by Django 5.2.13 on 2026-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoeditor', '0003_remove_projectvideorelease_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideorelease',
            name='pj_current_config',
            field=models.JSONField(blank=True, default=list, verbose_name='Текущие рабочие настройки (черновик в редакторе)'),
        ),
    ]
