# Generated by Django 5.2.13 on 2026-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('provider', models.CharField(max_length=50, verbose_name='AI провайдер')),
                ('style', models.CharField(blank=True, choices=[('DOCUMENTARY', 'Documentary'), ('SHOCK', 'Shock'), ('THEORY', 'Theory')], max_length=20, verbose_name='Выбранный стиль')),
                ('hook', models.TextField(blank=True, verbose_name='Hook')),
                ('voiceover', models.TextField(blank=True, verbose_name='Текст озвучки')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ AI')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'Генерация'), ('script_ready', 'Сценарий готов'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'TikTok сценарий',
                'verbose_name_plural': 'TikTok сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст сцены')),
                ('image_prompt', models.TextField(verbose_name='Промпт картинки')),
                ('duration', models.PositiveIntegerField(default=3, verbose_name='Длительность, сек')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='shorts.shortproject')),
            ],
            options={
                'verbose_name': 'Сцена TikTok',
                'verbose_name_plural': 'Сцены TikTok',
                'ordering': ['order'],
                'unique_together': {('project', 'order')},
            },
        ),
    ]
