# Generated by Django 5.2.13 on 2026-06-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_alter_language_options'),
        ('topics', '0005_alter_researchproject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сюжета')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг (URL)')),
                ('story_data', models.JSONField(blank=True, default=dict, help_text='Сырой JSON от Story Planner: hook, structure, selected_facts...', verbose_name='Структура сюжета (JSON)')),
                ('virality_score', models.PositiveSmallIntegerField(default=0, verbose_name='Вирусный потенциал (1-10)')),
                ('narrative_style', models.CharField(blank=True, max_length=50, verbose_name='Стиль повествования')),
                ('provider', models.CharField(default='openai', max_length=50, verbose_name='AI провайдер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('script_generated', 'Сценарий создан'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cluster', models.ForeignKey(blank=True, help_text='Глобальная тема или ниша (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_plans', to='article.articlecluster')),
                ('research_project', models.ForeignKey(help_text='Исходные исследовательские данные, на которых основан план', on_delete=django.db.models.deletion.CASCADE, related_name='story_plans', to='topics.researchproject')),
            ],
            options={
                'verbose_name': 'Сюжетный план (Story Plan)',
                'verbose_name_plural': 'Сюжетные планы',
                'ordering': ['-virality_score', '-created_at'],
            },
        ),
    ]
